LINUX:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/LINUX/**'
    - 'ALUMNOS/MIA/*/LINUX/**'

DOCKER:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/DOCKER/**'
    - 'ALUMNOS/MIA/*/DOCKER/**'

PYTHON:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/PYTHON/**'
    - 'ALUMNOS/MIA/*/PYTHON/**'

SQL:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/SQL/**'
    - 'ALUMNOS/MIA/*/SQL/**'

AHORCADO:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/AHORCADO/**'
    - 'ALUMNOS/MIA/*/AHORCADO/**'

APIS:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/APIS/**'
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/APIs/**'
    - 'ALUMNOS/MIA/*/APIS/**'
    - 'ALUMNOS/MIA/*/APIs/**'

DBT:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/DBT/**'
    - 'ALUMNOS/MIA/*/DBT/**'

KAFKA:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/KAFKA/**'
    - 'ALUMNOS/MIA/*/KAFKA/**'

DEMO:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/DEMO/**'
    - 'ALUMNOS/MIA/*/DEMO/**'

TICTACTOE:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/TICTACTOE/**'
    - 'ALUMNOS/MIA/*/TICTACTOE/**'

CHAT:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/CHAT/**'
    - 'ALUMNOS/MIA/*/CHAT/**'

CHATBIG:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/CHATBIG/**'
    - 'ALUMNOS/MIA/*/CHATBIG/**'

CHUCK:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/CHUCK/**'
    - 'ALUMNOS/MIA/*/CHUCK/**'

PYSPARK:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/PYSPARK/**'
    - 'ALUMNOS/MIA/*/PYSPARK/**'

TERRAFORM:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/TERRAFORM/**'
    - 'ALUMNOS/MIA/*/TERRAFORM/**'

AWS_ALMACENAMIENTO:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/AWS_ALMACENAMIENTO/**'
    - 'ALUMNOS/MIA/*/AWS_ALMACENAMIENTO/**'

AWS_ESPECIFICOS:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/AWS_ESPECIFICOS/**'
    - 'ALUMNOS/MIA/*/AWS_ESPECIFICOS/**'

GCP_ALMACENAMIENTO:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/GCP_ALMACENAMIENTO/**'
    - 'ALUMNOS/MIA/*/GCP_ALMACENAMIENTO/**'

GCP_ESPECIFICOS:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/GCP_ESPECIFICOS/**'
    - 'ALUMNOS/MIA/*/GCP_ESPECIFICOS/**'

CLUSTERING:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/CLUSTERING/**'
    - 'ALUMNOS/MIA/*/CLUSTERING/**'

SPOTY:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/SPOTY/**'
    - 'ALUMNOS/MIA/*/SPOTY/**'

VALENCIA:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/VALENCIA/**'
    - 'ALUMNOS/MIA/*/VALENCIA/**'

ML0_INTRO:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/ML0_INTRO/**'
    - 'ALUMNOS/MIA/*/ML0_INTRO/**'

ML1_REG:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/ML1_REG/**'
    - 'ALUMNOS/MIA/*/ML1_REG/**'

ML2_CLA:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/ML2_CLA/**'
    - 'ALUMNOS/MIA/*/ML2_CLA/**'

ML3_CLUSTERING:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/ML3_CLUSTERING/**'
    - 'ALUMNOS/MIA/*/ML3_CLUSTERING/**'

ML4_DIM:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/ML4_DIM/**'
    - 'ALUMNOS/MIA/*/ML4_DIM/**'

MLLIB:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/MLLIB/**'
    - 'ALUMNOS/MIA/*/MLLIB/**'

MLOPS:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/MLOPS/**'
    - 'ALUMNOS/MIA/*/MLOPS/**'

RN1_ANN:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/RN1_ANN/**'
    - 'ALUMNOS/MIA/*/RN1_ANN/**'

RN2_CNN:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/RN2_CNN/**'
    - 'ALUMNOS/MIA/*/RN2_CNN/**'

RN3_RNN:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/RN3_RNN/**'
    - 'ALUMNOS/MIA/*/RN3_RNN/**'

RN4_NLP:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/RN4_NLP/**'
    - 'ALUMNOS/MIA/*/RN4_NLP/**'

ESTADISTICA:
- changed-files:
  - any-glob-to-any-file:
    - 'ALUMNOS/{MDIAA,MDIAB,MDES}/*/ESTADISTICA/**'
    - 'ALUMNOS/MIA/*/ESTADISTICA/**'

entregable:
- changed-files:
  - any-glob-to-any-file: 'ALUMNOS/**'

PROFESORES:
- changed-files:
  - any-glob-to-any-file: 'PROFESORES/**'
